import { hash } from "bcryptjs";
import { v4 as uuidv4 } from "uuid";
import { db } from "../../config/db.js";
import { users } from "../schema.js";

export async function seedUsers() {
  const password = await hash("Test@123", 10);

  const userData = [
    // Admin
    {
      userId: uuidv4(),
      firstName: "Admin",
      lastName: "User",
      email: "admin@healthcare.com",
      password,
      phoneNumber: "+1234567890",
      dateOfBirth: new Date(1980, 0, 1),
      role: "admin",
      isVerified: true,
      isActive: true,
    },
    // Doctors
    {
      userId: uuidv4(),
      firstName: "Sarah",
      lastName: "Smith",
      email: "sarah.smith@doctor.com",
      password,
      phoneNumber: "+1122334455",
      dateOfBirth: new Date(1985, 5, 15),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Kwame",
      lastName: "Asante",
      email: "kwame.asante@doctor.com",
      password,
      phoneNumber: "+233201234567",
      dateOfBirth: new Date(1982, 2, 11),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Ama",
      lastName: "Osei",
      email: "ama.osei@doctor.com",
      password,
      phoneNumber: "+233209876543",
      dateOfBirth: new Date(1987, 8, 23),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Kofi",
      lastName: "Boateng",
      email: "kofi.boateng@doctor.com",
      password,
      phoneNumber: "+233241112233",
      dateOfBirth: new Date(1979, 10, 5),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Efua",
      lastName: "Mensah",
      email: "efua.mensah@doctor.com",
      password,
      phoneNumber: "+233271234567",
      dateOfBirth: new Date(1990, 1, 17),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Kojo",
      lastName: "Antwi",
      email: "kojo.antwi@doctor.com",
      password,
      phoneNumber: "+233551234567",
      dateOfBirth: new Date(1984, 3, 29),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Yaw",
      lastName: "Adu",
      email: "yaw.adu@doctor.com",
      password,
      phoneNumber: "+233501112222",
      dateOfBirth: new Date(1981, 6, 12),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Abena",
      lastName: "Kusi",
      email: "abena.kusi@doctor.com",
      password,
      phoneNumber: "+233561234567",
      dateOfBirth: new Date(1992, 9, 3),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Nana",
      lastName: "Owusu",
      email: "nana.owusu@doctor.com",
      password,
      phoneNumber: "+233591234567",
      dateOfBirth: new Date(1986, 11, 19),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Akua",
      lastName: "Appiah",
      email: "akua.appiah@doctor.com",
      password,
      phoneNumber: "+233541234567",
      dateOfBirth: new Date(1991, 4, 8),
      role: "doctor",
      isVerified: true,
      isActive: true,
    },
    // Patients
    {
      userId: uuidv4(),
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@patient.com",
      password,
      phoneNumber: "+1987654321",
      dateOfBirth: new Date(1990, 10, 20),
      role: "patient",
      isVerified: true,
      isActive: true,
    },
    {
      userId: uuidv4(),
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@patient.com",
      password,
      phoneNumber: "+1654321987",
      dateOfBirth: new Date(1995, 3, 5),
      role: "patient",
      isVerified: true,
      isActive: true,
    },
  ];

  const insertedUsers = await db.insert(users).values(userData).returning();

  console.log(`👥 Seeded ${insertedUsers.length} users`);
  return insertedUsers;
}
